replicaCount: 1

image:
  repository: ofekmalul/web_app
  pullPolicy: IfNotPresent
  tag: "1.0.1"

myLabel: 'web-app'

service:
  name: web-app-service
  type: ClusterIP
  port: 80
  targetPort: 9090

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: public-alb-terraform-eks-cluster
    alb.ingress.kubernetes.io/group.name: public-1
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hostname: www.ofek.com
  path: /
  class: alb
  pathType: Prefix # means that the path in the http request must start with /
